# Site settings
title: Sandeep Raju
header-img: img/home-bg.jpg
email: me@sandeepraju.in
description: "a place for my thoughts on every darn thing under the sun"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia
disqus_shortname: DisqusNameHere

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
